title: Peter Tadrous
logo: /assets/img/peter-tadrous-profile.jpg
author:
  name: Peter Tadrous
  email: peter.tadrous@gmail.com

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Navigation
# List links that should appear in the site sidebar here
navigation:
  - text: Introduction
    internal: true
    url: ./index
  - text: About
    internal: true
    url: about
  - text: Projects
    internal: true
    url: projects
  - text: Contact
    internal: true
    url: contact

# GitHub Pages settings
github:
  is_project_page: false
  repository_nwo: petertadrous/data-science-portfolio
  owner_name: Peter Tadrous
  owner_url: https://github.com/petertadrous
  repository_url: https://github.com/petertadrous/data-science-portfolio
