# Theme / Plugins
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Set the default layout for your pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false

main:
  - title: "Introduction"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/


# # Navigation
# # List links that should appear in the site sidebar here
# navigation:
#   - text: Introduction
#     internal: true
#     url: ./index
#   - text: About
#     internal: true
#     url: about
#   - text: Projects
#     internal: true
#     url: projects
#   - text: Contact
#     internal: true
#     url: contact

# # GitHub Pages settings
# github:
#   is_project_page: false
#   is_user_page: true
#   repository_nwo: petertadrous/data-science-portfolio
#   owner_name: Peter Tadrous
#   owner_url: https://github.com/petertadrous
#   repository_url: https://github.com/petertadrous/data-science-portfolio



minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Peter Tadrous"
title_separator          : "|"
# subtitle                 : # site tagline that appears below site title in masthead
name                     : "Peter Tadrous"
description              : "Data Science Portfolio."
url                      : https://petertadrous.com
repository               : petertadrous/data-science-portfolio"
# teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
# masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
# reCaptcha:
#   siteKey                :
#   secret                 :
# atom_feed:
#   path                   : # blank (default) uses feed.xml
#   hide                   : # true, false (default)
# search                   : # true, false (default)
# search_full_content      : # true, false (default)
# search_provider          : # lunr (default), algolia, google
# lunr:
#   search_within_pages    : # true, false (default)
# algolia:
#   application_id         : # YOUR_APPLICATION_ID
#   index_name             : # YOUR_INDEX_NAME
#   search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
#   powered_by             : # true (default), false
# google:
#   search_engine_id       : # YOUR_SEARCH_ENGINE_ID
#   instant_search         : # false (default), true
# # SEO Related
# google_site_verification :
# bing_site_verification   :
# naver_site_verification  :
# yandex_site_verification :
# baidu_site_verification  :

# # Social Sharing
# twitter:
#   username               :
# facebook:
#   username               :
#   app_id                 :
#   publisher              :
# og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
# social:
#   type                   : # Person or Organization (defaults to Person)
#   name                   : # If the user or organization name differs from the site's name
#   links: # An array of links to social media profiles

# # Analytics
# analytics:
#   provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id          :
#     anonymize_ip         : # true, false (default)

# Author information
author:
  name: "Peter Tadrous"
  avatar: "/assets/img/peter-tadrous-profile.jpg"
  bio: "Data Scientist | Machine Learning Engineer"
  location: "Queens, NY"
  email: "peter@petertadrous.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:peter@petertadrous.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/petertadrous"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/peter-t/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/your-twitter-handle"


# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:peter@petertadrous.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/petertadrous"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/peter-t/"


# # Reading Files
# include:
#   - .htaccess
#   - _pages
# exclude:
#   - "*.sublime-project"
#   - "*.sublime-workspace"
#   - vendor
#   - .asset-cache
#   - .bundle
#   - .jekyll-assets-cache
#   - .sass-cache
#   - assets/js/plugins
#   - assets/js/_main.js
#   - assets/js/vendor
#   - Capfile
#   - CHANGELOG
#   - config
#   - Gemfile
#   - Gruntfile.js
#   - gulpfile.js
#   - LICENSE
#   - log
#   - node_modules
#   - package.json
#   - package-lock.json
#   - Rakefile
#   - README
#   - tmp
#   - /docs # ignore Minimal Mistakes /docs
#   - /test # ignore Minimal Mistakes /test
# keep_files:
#   - .git
#   - .svn
# encoding: "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# # Conversion
# markdown: kramdown
# highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false


# # Markdown Processing
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false


# # Sass/SCSS
# sass:
#   sass_dir: _sass
#   style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# # Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# timezone: America/New_York

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache




# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


