# Theme / Plugins
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Set the default layout for your pages
defaults:
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      toc: false
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

# Reading Files
include:
  - _pages
exclude:
  - README

sidebar:
  nav: "main"
# # Navigation
# # List links that should appear in the site sidebar here
# navigation:
#   - text: Introduction
#     internal: true
#     url: ./index
#   - text: About
#     internal: true
#     url: about
#   - text: Projects
#     internal: true
#     url: projects
#   - text: Contact
#     internal: true
#     url: contact

# # GitHub Pages settings
# github:
#   is_project_page: false
#   is_user_page: true
#   repository_nwo: petertadrous/data-science-portfolio
#   owner_name: Peter Tadrous
#   owner_url: https://github.com/petertadrous
#   repository_url: https://github.com/petertadrous/data-science-portfolio



minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Peter Tadrous"
title_separator          : "|"
# subtitle                 : # site tagline that appears below site title in masthead
name                     : "Peter Tadrous"
description              : "Data Science Portfolio."
url                      : https://petertadrous.com
repository               : petertadrous/data-science-portfolio
# teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
# masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)

# Author information
author:
  name: "Peter Tadrous"
  avatar: "/assets/img/peter-tadrous-profile.jpg"
  bio: Data Scientist, Machine Learning Engineer
  location: "Queens, NY"
  email: "peter@petertadrous.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/petertadrous"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/peter-t/"


# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:peter@petertadrous.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/petertadrous"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/peter-t/"

timezone: America/New_York

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


