### Site Settings ###
title               : Peter Tadrous
description         : >-
                      Data Scientist, Machine Learning Engineer<br>
                      Harnessing the power of data to uncover hidden patterns and drive informed decision-making.
baseurl             : ""
repository          : petertadrous/data-science-portfolio
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Peter Tadrous
  image             : https://avatars.githubusercontent.com/u/70548761
  bio               : Data Scientist, Machine Learning Engineer
  location          : Queens, NY
  email             : peter.tadrous@gmail.com
  github            : petertadrous
# kaggle            : your_username
  linkedin          : peter-t
# medium            : your_username
# stackoverflow     : your_user_id
# twitter           : your_username
# youtube           : your_channel_name


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


# ### Analytics ###
# analytics:
#   enabled: false
#   google:
#     tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: petertadrous
  color: "#007bff"
  message: "Thank you for visiting."
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false


### Exclude from processing ###
exclude:
  - README.md

### GitHub Pages settings ###
github:
  is_project_page: false
  is_user_page: true
  repository_nwo: petertadrous/data-science-portfolio
  owner_name: Peter Tadrous
  owner_url: https://github.com/petertadrous
  repository_url: https://github.com/petertadrous/data-science-portfolio
